### ISSUE TITLE
expand-web-form has trouble with dotted lists

### ISSUE THREAD

**Issue by alanruttenberg** [jingtaozf/literate-lisp#4]
(expand-web-form '(a . b))
->The value b is not of type list.

Found when my patch compile-defun tried to compile fiveam.

**Comment by jingtaozf** [comment]
It has been fixed in this commit: https://github.com/jingtaozf/literate-lisp/commit/64d4835acebc71166287f14a2d6df3bb43bafa26

When developing literate-lisp iteself, I will load it firstly then update the file tangle.org directly, after the testing of integrity of tangle.org, I will release it to tangle.lisp, so I can write literate-lisp by the literate style.

**Comment by alanruttenberg** [comment]
Thanks!
